version: "3"
services:
  crm-client:
    container_name: crmclient
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
