export const paths = {
    root: '/',
    orders: '/orders',
    notfound: '*',
    users: '/users',
    closeOrder: '/closeOrder/:chatId/:messageId/:orderId',
    login: '/login',
    profile: '/profile',
    workOrder: '/work/:chatId/:messageId/:orderId',
    activeOrders: '/activeOrders',
    sdOrdersPage: '/takeToSD',
    paymentOrdersPage: '/paymentOrders',
    editOrder: '/editOrder/:id',
    createOrder: '/createNewOrder',
    orderInfo: '/orderInfo/:id',
};
